#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

[ "${DIB_INSTALLTYPE_amphora_agent:-}" = "package" ] && exit 0

awk 'FNR == 1 {print $1}' /opt/amphora-agent/.git/logs/HEAD >> /opt/amphora-agent.gitref
rm -rf /opt/amphora-agent

case $DISTRO_NAME in
    ubuntu | debian )
        apt-get --assume-yes purge --auto-remove
    ;;
    fedora | centos* | rhel* )
        YUM=${YUM:-yum}
        ${YUM} -v -y autoremove
    ;;
    *)
        echo "ERROR: Unsupported distribution $DISTRO_NAME"
        exit 1
    ;;
esac
