#!/bin/bash

# Override resolv.conf file from DIB with a custom one.
# Having at least one nameserver is now required by dnfpython (>=)
echo "nameserver 127.0.0.1" > /etc/resolv.conf
echo "nameserver 127.0.0.1" > /etc/resolv.conf.ORIG
if [ -d /etc/dhcp/dhclient-enter-hooks.d ]
then
    # Debian/Ubuntu
    echo "#!/bin/sh
make_resolv_conf() { : ; }" > /etc/dhcp/dhclient-enter-hooks.d/noresolvconf
    chmod +x /etc/dhcp/dhclient-enter-hooks.d/noresolvconf
    rm -f /etc/dhcp/dhclient-enter-hooks.d/resolvconf
else
    # RHEL/CentOS/Fedora
    echo "#!/bin/sh
make_resolv_conf() { : ; }" > /etc/dhcp/dhclient-enter-hooks
    chmod +x /etc/dhcp/dhclient-enter-hooks
fi

if [ -e /etc/nsswitch.conf ]; then
    sed -i -e "/hosts:/ s/dns//g" /etc/nsswitch.conf
fi
