#!/bin/bash

set -eu
set -o xtrace

if [[ "$DISTRO_NAME" == "centos" && "$DIB_RELEASE" == "8-stream" ]]; then
    dnf install -y dnf-plugins-core centos-release-nfv-common
    # REVISIT(cgoncalves): replace arch if-else + GPG with release RPM once available
    if [[ "$ARCH" =~ (aarch64|arm64) ]]; then
        yum_arch=aarch64
    elif [[ "$ARCH" =~ (ppc64le|ppc64el) ]]; then
        yum_arch=ppc64le
    elif [[ "$ARCH" =~ (x86_64|amd64) ]]; then
        yum_arch=x86_64
    else
        echo "ERROR: Unsupported architecture $ARCH"
        exit 1
    fi
    dnf config-manager --add-repo http://mirror.centos.org/centos/$DIB_RELEASE/nfv/${yum_arch}/network-extras
    echo gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-NFV >> /etc/yum.repos.d/mirror.centos.org_centos_${DIB_RELEASE}_nfv_*_network-extras.repo
fi
