#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

case $DISTRO_NAME in
    fedora | centos* | rhel* )
        systemctl disable dnf-makecache.timer || true
    ;;
    *)
        echo "ERROR: Unsupported distribution $DISTRO_NAME"
        exit 1
    ;;
esac
