#!/bin/bash

#
# Copyright Red Hat
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -euo pipefail

case $DISTRO_NAME in
    ubuntu | debian | fedora | centos* | rhel* )
        DIB_BOOTLOADER_DEFAULT_CMDLINE+=" irqaffinity=0"
        # This will be ignored on single vCPU systems
        DIB_BOOTLOADER_DEFAULT_CMDLINE+=" isolcpus=1-N"
        DIB_BOOTLOADER_DEFAULT_CMDLINE+=" nohz=on nohz_full=1-N"
        export DIB_BOOTLOADER_DEFAULT_CMDLINE
    ;;
    *)
        echo "ERROR: Unsupported distribution $DISTRO_NAME"
        exit 1
    ;;
esac
