  # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ stable/2025.1-m3 ]
  pull_request:
    branches: [ stable/2025.1-m3 ]

env:
  TOX_CONSTRAINTS_FILE: https://raw.githubusercontent.com/sapcc/requirements/stable/2025.1-m3/upper-constraints.txt

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.12]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          set -ex
          sudo apt-get -y update
          sudo apt-get -y install build-essential netbase
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Run Tox
        run: tox -e py3,functional-py312
